# Generated by Django 4.1 on 2022-08-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0017_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
