# Generated by Django 4.1 on 2022-08-31 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0023_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
