# Generated by Django 4.1 on 2022-08-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0025_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='massage',
            field=models.TextField(default=1, max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.IntegerField(default='+998'),
        ),
    ]
